#!/usr/bin/env bash
# Sets up a local PostgreSQL database for Bytenut and writes .env
set -e

WORKSPACE_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$WORKSPACE_DIR/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${CYAN}[db]${NC} $*"; }
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

DB_NAME="bytenut"
DB_USER="postgres"
DB_PASS="bytenut123"
DB_PORT="5432"

# ── Install PostgreSQL if missing ──────────────────────────────────────────
if ! command -v psql &>/dev/null; then
  info "Installing PostgreSQL..."
  apt-get update -qq && apt-get install -y -qq postgresql postgresql-client
  ok "PostgreSQL installed"
else
  ok "PostgreSQL found: $(psql --version | head -1)"
fi

# ── Detect PostgreSQL version ──────────────────────────────────────────────
PG_VERSION=$(pg_lsclusters -h 2>/dev/null | awk '{print $1}' | head -1)
if [ -z "$PG_VERSION" ]; then
  # Fallback: get version from installed binaries
  PG_VERSION=$(ls /usr/lib/postgresql/ 2>/dev/null | sort -V | tail -1)
fi
[ -z "$PG_VERSION" ] && die "Cannot determine PostgreSQL version"
info "PostgreSQL version: $PG_VERSION"

# ── Create cluster if none exists ──────────────────────────────────────────
CLUSTER_COUNT=$(pg_lsclusters -h 2>/dev/null | grep -c "." || echo 0)
if [ "$CLUSTER_COUNT" -eq 0 ]; then
  info "No cluster found — creating 'main' cluster..."
  pg_createcluster "$PG_VERSION" main --start
  ok "Cluster created and started"
else
  PG_CLUSTER=$(pg_lsclusters -h 2>/dev/null | awk '{print $2}' | head -1)
  STATUS=$(pg_lsclusters -h 2>/dev/null | awk '{print $4}' | head -1)
  info "Cluster: $PG_VERSION/$PG_CLUSTER (status: $STATUS)"
  if [ "$STATUS" != "online" ]; then
    info "Starting cluster..."
    pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" start
  else
    ok "Cluster already online"
  fi
fi

# ── Wait for PostgreSQL to be ready ───────────────────────────────────────
info "Waiting for PostgreSQL..."
for i in $(seq 1 20); do
  pg_isready -q 2>/dev/null && break
  sleep 1
  echo -n "."
done
echo ""
pg_isready 2>/dev/null || die "PostgreSQL did not become ready — check: pg_lsclusters"
ok "PostgreSQL is ready"

# ── Set postgres password & create database ───────────────────────────────
info "Configuring database '$DB_NAME'..."
su - postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD '$DB_PASS';\"" 2>/dev/null \
  || warn "Could not set postgres password (may already be set)"

su - postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname='$DB_NAME'\" | grep -q 1 \
  || createdb $DB_NAME" 2>/dev/null
ok "Database '$DB_NAME' is ready"

# ── Write .env ────────────────────────────────────────────────────────────
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:${DB_PORT}/${DB_NAME}"

if [ -f "$ENV_FILE" ]; then
  if grep -q "^DATABASE_URL=" "$ENV_FILE"; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=${DATABASE_URL}|" "$ENV_FILE"
  else
    echo "DATABASE_URL=${DATABASE_URL}" >> "$ENV_FILE"
  fi
  ok ".env updated"
else
  cat > "$ENV_FILE" <<EOF
# Bytenut environment — auto-generated by setup-db.sh
DATABASE_URL=${DATABASE_URL}

# Optional: residential proxy for bytenut.com auth (leave blank if not using)
# PROXY_HOST=
# PROXY_PORT=
# PROXY_USERNAME=
# PROXY_PASSWORD=
# PROXY_PROTOCOL=https
EOF
  ok ".env created"
fi

echo ""
echo -e "  ${CYAN}DATABASE_URL${NC} = $DATABASE_URL"
echo ""
ok "Database setup complete — run: bash start.sh"
